### ISSUE TITLE
How can I get the xfft_512_sim_netlist.v?

### ISSUE THREAD

**Issue by FishSeeker** [lxschwalb/fpga_mel_filter_bank#3]

**Comment by lxschwalb** [comment]
it is located in /srcs/sources_1/ip/xfft_512/

**Comment by FishSeeker** [comment]
> it is located in /srcs/sources_1/ip/xfft_512/

I mean how can I generate the .v file from the FFT ip core. The xfft_512_sim_netlist.v is not auto-generated by vivado, is it right?

**Comment by lxschwalb** [comment]
I think it is if I remember correctly. I cannot remember the exact process though. I can have a look at it this weekend if necessary

**Comment by FishSeeker** [comment]
> I think it is if I remember correctly. I cannot remember the exact process though. I can have a look at it this weekend if necessary

Thanks so much. And if you know how to compile this project by VCS?

**Comment by lxschwalb** [comment]
I just confirmed that the *_sim_netlist.v files are automatically generated by vivado when the ip is created. I don't know anything about VCS

**Comment by FishSeeker** [comment]
> I just confirmed that the *_sim_netlist.v files are automatically generated by vivado when the ip is created. I don't know anything about VCS

Thanks.
